---
title: "stl_lead_mw"
format: html
editor: visual
execute: 
  warning: FALSE
---

## Day 1 Activity

```{r}
library(tidyverse)
library(janitor)
```

```{r}
stl_lead <- read_csv(here::here("data", "stl_lead.csv")) %>% 
  clean_names()
                       
```

```{r}
summary(stl_lead)
head(stl_lead)
dim(stl_lead)
```

```{r}
stl_lead_prop <- data.frame(stl_lead) %>% 
  dplyr::mutate(prop_white = (white / total_pop) * 100)
```

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = prop_white)) +
  geom_point() +
  labs(x = "Percentage of children with elevated blood lead levels", y = "Percent of census track identifying as white", title = "Elevated blood lead levels in Census tract")
stl_lead_plot


```

```{r}
ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)
```

```{r}
stl_lead_histogram <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(color = "blue", fill = "pink")

stl_lead_histogram

ggsave(here::here("figs", "stl_lead_histogram.jpg"), height = 5, width = 6)
```
